security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
      algorithm: auto
      cost: 15

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false


    main:
      form_login:
        login_path: app_login
        check_path: app_login
        enable_csrf: true
        default_target_path: /explorer
      logout:
        path: app_logout
        target: app_explorer

  #   main:
  #     # pattern: ^/login
  #     pattern: ^/(?!api)
  #     lazy: true
  #     provider: app_user_provider
  #     form_login:
  #       login_path: login
  #       check_path: login
  #       default_target_path: /explorer
  #     logout:
  #       path: /logout

    # api_login:
    #   pattern: ^/api/login
    #   stateless: true
    #   provider: app_user_provider
    #   json_login:
    #     check_path: /api/login
    #     success_handler: lexik_jwt_authentication.handler.authentication_success
    #     failure_handler: lexik_jwt_authentication.handler.authentication_failure

    # api:
    #   pattern: ^/api
    #   stateless: true
    #   provider: app_user_provider
    #   jwt: ~

  access_control:
    # - { path: ^/api/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    # - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
    # - { path: ^/user, roles: ROLE_USER }
    # - { path: ^/admin, roles: ROLE_ADMIN }
