services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: blendsk_app
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    environment:
      DATABASE_URL: "mysql://root:root@db:3306/blendsk?serverVersion=8.0.32&charset=utf8mb4"
    restart: unless-stopped

  database:
    image: mysql:8.0
    restart: always
    container_name: blendsk_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: blendsk
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
